export const SolutionsActionTypes = {
  SET_SOLUTIONS: 'SET_SOLUTIONS',
  PAIR_ORGANIZATION_WITH_SOLUTION: 'PAIR_ORGANIZATION_WITH_SOLUTION',
  REMOVE_SOLUTION: 'REMOVE_SOLUTION',
  APPROVE_SOLUTION: 'APPROVE_SOLUTION',
};
