export const SolutionsActionTypes = {
  SET_SOLUTIONS: 'SET_SOLUTIONS',
  PAIR_ORGANIZATIONS_WITH_SOLUTIONS: 'PAIR_ORGANIZATIONS_WITH_SOLUTIONS',
  REMOVE_SOLUTION: 'REMOVE_SOLUTION',
  APPROVE_SOLUTION: 'APPROVE_SOLUTION',
  MODIFY_SOLUTION: 'MODIFY_SOLUTION',
  ADD_SOLUTION: 'ADD_SOLUTION',
};
